name = "questions-durable-objects"
compatibility_date = "2022-02-12"

[dev]
port = 3000

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"

[[migrations]]
tag = "v1"
new_classes = ["Game"]
